import { useState } from "react";

const Legal = () => {
  const [showTerms, setShowTerms] = useState(false);
  const [showPolicy, setShowPolicy] = useState(false);

  const toggleTerms = () => {
    setShowTerms(!showTerms);
  };

  const togglePolicy = () => {
    setShowPolicy(!showPolicy);
  };

  return (
    <div>
      <hr className="border-t border-gray-400 w-[100%] mx-auto" />
      <div className="flex justify-between px-2 md:px-32 pt-5 mb-10 text-gray-400 flex-col md:flex-row text-center">
        <p
          onClick={toggleTerms}
          className="cursor-pointer hover:underline hover:text-black transition-all duration-300">
          Terms and Conditions
        </p>
        <p
          onClick={togglePolicy}
          className="cursor-pointer hover:underline hover:text-black transition-all duration-300 pt-3 pb-8 md:py-0">
          Privacy Policy
        </p>
        <p className=" ">Copyright © 2022 Cinematic FPV. All rights reserved</p>
      </div>
      {showTerms && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center z-50">
          <div className="bg-white w-[90%] h-[90%]  p-8 relative">
            <button
              onClick={toggleTerms}
              className="absolute top-10 right-10 md:right-24 cursor-pointer border border-gray-400 rounded-full px-8 py-2">
              Close
            </button>

            <h1 className="text-lg md:text-3xl text-center fixed pt-3">Terms and Conditions</h1>
          </div>

          <div className="overflow-auto w-[90%] h-[73%] mt-14 px-8 absolute">
            <p>
              BACKGROUND AND PURPOSE Foleon’s leading content creation platform empowers business
              teams to create engaging and intelligent content experiences at scale. Organizations
              use Foleon to produce bespoke content for every stage of the customer journey and give
              buyers the flexibility to self-educate and consume content at their own pace. The
              purpose of this Agreement is to define the terms and conditions under which FOLEON
              B.V., registered office in Amsterdam, the Netherlands, listed with the Commercial
              Register of the Chamber of Commerce under file reference number 58585680, hereinafter
              referred to as “Foleon”, shall provide the Service(s) and potential Professional
              Services to the Customer (hereafter referred to as “Customer”) in exchange for payment
              for the services. All agreements between Foleon and the Customer are subject to these
              terms and conditions (hereinafter referred to as “Agreement”). 1. DEFINITIONS Unless
              otherwise defined herein, all capitalized terms used within this Agreement have the
              following meaning: 1.1. “Active Use” refers to data stored within the Service under a
              current Order Form or within three (3) months of the expiration of the most recent
              Order Form. 1.2. “Acceptable Use Policy” refers to the Foleon Acceptable Use Policy
              (AUP), updated from time to time, and available at AUP
              (https://www.foleon.com/acceptable-use-policy-2021-01-01). 1.3. “Add-On” means
              integrations, applications, and other add-ons that are used with the Service(s). 1.4.
              “Affiliate(s)” means any entity which is controlled by, in control of, or is under
              common control with a Party to this Agreement, where “control” means either the power
              to direct the management or affairs of the entity or ownership of 50% or more of the
              voting securities of the entity. For Foleon, Affiliate(s) shall also include the
              subcontractors referenced in Section 20.4 (Subcontractors). 1.5. “Aggregate/Anonymous
              Data” means (i) data generated by aggregating Customer Data so that results are
              non-personally identifiable with respect to the Customer or any natural person; and
              (ii) learnings, logs, and data regarding the use of the Service(s). 1.6. “Authorized
              Users” means the Customer’s employees and contractors (such as Agencies or management
              consultants) who have or may be assigned a Seat to access and use the Service and who
              are acting for the Customer’s benefit and on its behalf. 1.7. “Confidential
              Information” means information that is owned or possessed by a Party, its Affiliates
              or Personnel that either is marked as “confidential” or “proprietary” or otherwise due
              to its nature reasonably would be deemed to be confidential, and that is disclosed or
              accessed pursuant to this Agreement. 1.8. “Content” means text, images, videos, or
              other content uploaded or integrated with the Service by Customer. 1.9. “Agreement”
              means this subscription Agreement document and its annexes, appendices, schedules, and
              amendments, including any Order Forms and service-specific terms as well as any
              policies or exhibits linked to or referenced herein. 1.10. “Customer” means a company
              with a current agreement with Foleon for the purchase of Service(s) or a user of a
              free trial version of Foleon. 1.11. “Customer Data” means: (i) Content; (ii) Submitted
              Data; and (iii) Visitor Data. 1.12. “Customer's Administrators” means the Authorized
              Users that have been provided with administrator permissions within the Service(s).
              Customer’s Administrators have broader user permissions to the Service than regular
              Authorized Users. 1.13. “Personnel” means employees, agents, consultants, contractors,
              and subcontractors, together with the personnel of any of the foregoing. 1.14. “DPA”
              means the Foleon Data Processing Agreement, including, to the extent applicable, the
              Standard Contractual Clauses (Controller – Processor). 1.15. “Documentation” means the
              technical documentation created and provided by Foleon in connection with the Service,
              available at learn.foleon.com. 1.16. “Foleon Technology” means the Service and any and
              all related or underlying Intellectual Property Rights, Documentation, technology,
              code, know-how, logos and templates (including any reports or output obtained from the
              Service(s)), anything delivered as part of customer support or other services, and any
              updates, modifications or derivative works of any of the foregoing. 1.17.
              “Intellectual Property Rights” mean copyrights, software, domain names, trademarks,
              service marks, designs and registrations and applications thereof, data, and
              Documentation thereof, trade secrets, and know-how (including but not limited to
              development information, specifications, plans, proposals, and technical data). 1.18.
              “Service(s)” means the specific proprietary Software as a Services (SaaS) product(s)
              of Foleon specified in the Customer’s Order Form, including any related Foleon
              Documentation, and excluding any Third-Party Products. The Service(s) include access
              to the features and functionalities made available by Foleon from time to time. 1.19.
              “Service Level Agreement” means the Foleon Service Level Agreement (SLA), updated from
              time to time, and available at SLA
              (https://www.foleon.com/service-level-agreement-2021-01-01). 1.20. “Support Services”
              means technical support services offered by Foleon for the Service(s) specified in the
              Order Form, Order Form exhibit, or other document referencing this Agreement. 1.21.
              “Order Form” means any Foleon ordering Documentation or online sign-up or subscription
              flow that references this Agreement. 1.22. “Party” means Foleon or Customer. “Parties”
              mean Foleon and Customer. 1.23. “Professional Services” means any non-subscription
              paid Services specified in an Order Form, Order Form exhibit, or other document
              referencing this Agreement. Professional Services can include onboarding,
              implementation, training, design, and consulting services offered by Foleon. 1.24.
              “Foleon Doc(s)” means Content assets that are created and published using Foleon
              Service(s). 1.25. “Scope of Use” means the usage limits or other scope of use
              descriptions for the Service included in the applicable Order Form (including
              descriptions of packages and features) or Documentation, including any numerical
              limits on Seats/Authorized Users, Foleon Docs, or Teams. 1.26. “Submitted Data” means
              data uploaded or otherwise submitted by the Customer to the Service, including
              Third-Party Content. 1.27. “Subscription Term” means the initial term for the
              subscription to the applicable Service, as specified on the Customer’s Order Form(s),
              and each subsequent renewal term (if any). 1.28. “Seat(s)” or “Account(s)” means each
              individual user account granting access to the Service as assigned or assignable by
              the Customer’s Administrator via the users panel within the Service(s). 1.29. “Teams”
              means departments or business units that work independently from each other within a
              single Foleon Account using Foleon’s Team structure. 1.30. “Third-Party” means any
              party that is not the Customer, Foleon, an Affiliate of the Customer, or Foleon
              subcontractor. 1.31. “Third-Party Content” means content, data or other materials that
              the Customer submits to the Service(s) from its Third-Party data providers, including
              through Add-Ons used by the Customer. 1.32. “Third-Party Product(s)” means any
              applications, integrations, software, code, online services, systems, other products,
              and Add-Ons not developed by Foleon. 1.33. “User Data” is the data collected from a
              user when they use the Foleon Service(s), including IP address, browser information,
              and/or header information. 1.34. “Visitor Data” is the data collected from a reader
              when accessing a Foleon Doc(s), including IP address, browser information, and/or
              header information. Other terms are defined in other Sections of this Subscription
              Agreement or in the relevant policies, or annexes. 2. PARTS OF THIS AGREEMENT 2.1.
              Incorporated documents – This Agreement consists of the following documents, some
              listed as Annexes to this Agreement, others as hyper-links, which are hereby
              incorporated by reference: 2.1.1. Each executed Order Form (Above) 2.1.2. Data
              Processing Agreement (“DPA”) – (https://www.foleon.com/hubfs/pdf/foleon-bv-dpa.pdf)
              2.1.3. Acceptable Use Policy (“AUP”) –
              (https://www.foleon.com/acceptable-use-policy-2021-01-01) 2.1.4. Service Level
              Agreement (“SLA”) – (https://www.foleon.com/service-level-agreement-2021-01-01) 3.
              ACCOUNT REGISTRATION AND USE 3.1. Account Information - All account information
              provided by the Customer must be accurate, current, and complete. 3.2. Credentials -
              The Customer must ensure that any user IDs, passwords, and other access credentials
              (such as API tokens) for the Service are kept strictly confidential and not shared
              with any unauthorized person. The Customer must notify Foleon immediately of any
              breach of security or unauthorized use of an account which the Customer has become
              aware of. Accounts are personal and must not be shared with others. If any Authorized
              User stops working for the Customer, the Customer must immediately terminate that
              person’s access to the Service. The Customer shall be responsible for any and all
              actions taken using the accounts, passwords, or access credentials designated to the
              Customer. 3.3. Authorized Administrator Access - The Customer is responsible for
              designating those individuals who are authorized to access the Customer’s
              Administrators' account(s). 3.4. Fair Use - Foleon wants to ensure optimal user
              experience for all Customers. To ensure this Foleon may, therefore, take the measure
              set out in the Acceptable Use Policy (currently available at
              https://www.foleon.com/acceptable-use-policy-2021-01-01) in the event it establishes
              additional usage as defined in the Acceptable Use Policy. 4. ACCESS TO THE SERVICE
              4.1. General Conditions - Subject to the compliance with this Agreement, Foleon grants
              to the Authorized Users of the Customer, non-exclusive, non-transferable,
              non-sublicensable right during the applicable Subscription Term to access and use the
              Service(s) designated on the Customer’s Order Form. The Service(s) may be used solely
              by the Customers. Use by Third-Parties, is not permitted unless otherwise agreed. For
              the avoidance of doubt, the Customers shall be responsible and liable for all
              Authorized Users’ use and access to the Service and their compliance with the terms
              and conditions of this Agreement and Foleon’s policies. 4.2. Developments - The
              Customer acknowledges that the Service constantly develops and evolves over time.
              Consequently, Foleon may, at its option, make updates, bug fixes, modifications or
              improvements to the Service from time to time. Updates to the Service can be found on
              the Foleon website (currently available at www.foleon.com/product-updates). Foleon
              will provide informational updates proactively about major changes to the Service
              through the in-product chat. Foleon may also make new applications, features or
              functionalities for the Services available from time to time, the use of which may be
              contingent upon the Customer's agreement to additional terms. 4.3. Trials and Betas –
              If Customer receives access to the Service or Service features on a free or trial
              basis or as an alpha, beta, or early access offering (“Trials and Betas”), use is
              permitted only for Customer’s internal evaluation during the period designated by
              Foleon (or if not designated, 30 days). Trials and Betas are optional and either party
              may terminate Trials and Betas at any time for any reason. Trials and Betas may be
              inoperable, incomplete or include features that Foleon may never release, and their
              features and performance information are Foleon’s Confidential Information.
              NOTWITHSTANDING ANYTHING ELSE IN THIS AGREEMENT, FOLEON PROVIDES TRIAL AND BETAS “AS
              IS” WITH NO WARRANTY, INDEMNITY OR SUPPORT AND ITS LIABILITY FOR TRIALS AND BETAS WILL
              NOT EXCEED EUR 50. 5. CUSTOMER OBLIGATIONS 5.1. Respecting Third Party Rights - The
              Customer represents and warrants that the collection, use, and disclosure of Customer
              Data will not violate any Third-Party rights, including Intellectual Property Rights,
              privacy, and publicity rights. If the Customer receives any takedown requests or
              infringement notices related to Customer Data or its use of Third-Party Products, it
              must promptly stop using the related item with the Foleon Service(s) and notify
              Foleon. If Foleon receives any takedown requests or infringement notices related to
              Customer Data or Customer’s use of Third-Party Products, Foleon will respond in
              accordance with applicable laws, including the Digital Millennium Copyright Act and
              Foleon policies, including immediate removal of the relevant Content from the
              Service(s), and will notify the Customer on the next steps. The Customer must not take
              any action that would cause Foleon or the Service(s) to become subject to any
              Third-Party terms (including open-source license terms). 5.2. Obtaining Consents - The
              Customer may have the ability to access, monitor, use, or disclose data available to
              Authorized Users within the Authorized Users’ Accounts. The Customer will obtain and
              maintain all required consents from Authorized Users to allow: (i) Customer's access,
              monitoring, use and disclosure of such data, and (ii) Foleon to provide the
              Service(s). 5.3. Acceptable Use Policy/Prohibited Use - Customer agrees that it shall
              abide by the terms of the AUP and the Customer shall undertake that its Authorized
              Users or any Third-Party within the reasonable control of the Customer, in any event
              including Customer Personnel, shall abide by the terms of the AUP. 5.4. Customer
              Affiliates – Customer’s Affiliates may use the Service as Authorized Users of
              Customer. Alternatively, an Affiliate of Customer may enter its own Order Form as
              mutually agreed with Foleon and this creates a separate agreement between Affiliate
              and Foleon that incorporates this Agreement with the Affiliate treated as Customer.
              Neither Customer nor Customer Affiliate has any rights under each other’s agreement
              with Foleon, and breach or termination of any such agreement is not breach nor
              termination under any other. 6. CUSTOMER DATA 6.1. Rights in Customer Data - As
              between the Parties, the Customer retains all right, title, and interest (including
              any Intellectual Property Rights) in and to the Customer Data (excluding any Foleon
              Technology). The Customer hereby grants Foleon a non-exclusive, worldwide,
              royalty-free right and license to collect, use, copy, store, transmit, modify, and
              create derivative works of the Customer Data solely to the extent necessary to provide
              the Service(s) and related services to the Customer. For Content, this includes the
              right to publicly display and perform Content (including derivative works and
              modifications) as directed by the Customer through the Service. This Section 6
              (Customer Data) does not however limit Foleon’s right to generate the
              Aggregate/Anonymous Data in accordance with Section 6.3 (Aggregate/Anonymous Data)
              below. 6.2. Third-Party Products and Customer Data - If the Customer installs or
              enables Third-Party Products not already embedded in the Services or Products for use
              with the Service, the Customer acknowledges that providers of those Third-Party
              Products may have access to Customer Data in connection with the interoperation and
              support of such Third-Party Products with the Service(s). To the extent the Customer
              authorizes the access or transmission of Customer Data through a Third-Party Product,
              Foleon will not be responsible for any use, disclosure, modification or deletion of
              such Customer Data. 6.3. Aggregate/Anonymous Data - Foleon will have the right to
              generate Aggregate/Anonymous Data from the Service(s). Aggregate/Anonymous Data shall
              be regarded as Foleon Technology, which Foleon may use for any business purpose during
              or after the term of this Agreement (including without limitation to develop and
              improve Foleon’s products and Service(s) and to create and distribute reports and
              other materials). For clarity, Foleon will only disclose Aggregate/Anonymous Data
              externally in a de-identified (anonymous) form that does not identify the Customer or
              Authorized Users, and that is stripped of all persistent identifiers (such as device
              identifiers, IP addresses, names, addresses, and cookie IDs). The Customer is not
              responsible for Foleon’s use of Aggregate/Anonymous Data. 6.4. No Archiving - Foleon
              does not provide an archiving service and Customer is responsible for appropriate
              archiving and backing up Content and its data (Customer Data). The Customer
              acknowledges that Foleon may delete Content no longer in Active Use. Additionally, the
              Customer acknowledges that Foleon may, by giving reasonable prior notice, delete such
              data relating to a feature of the Service(s) no longer being offered or made available
              as part of the Service(s). Foleon expressly disclaims all other obligations with
              respect to storage. 6.5. Data Export - During the Subscription Term or within 30 days
              thereafter, Customer may export its Content from the Service using the export features
              described in the Documentation. After this export period, Foleon may delete Content in
              accordance with its standard schedule and procedures. If Customer elects to
              proactively delete its account at any time, all associated Content will be deleted
              permanently and cannot be retrieved. 7. PERSONAL DATA AND DATA PROTECTION 7.1. DPA -
              In the course of providing the Service(s) to the Customer, Foleon may process certain
              personal data (as defined in the EU General Data Protection Regulation 2016/679) on
              behalf of the Customer. Such processing shall be subject to the DPA. Each Party agrees
              to comply with the DPA. 8. SUPPORT/PROFESSIONAL SERVICES 8.1. Provision of Support
              Services - Foleon makes available web-based support through the Service(s) in addition
              to email support (available at support@foleon.com). Additional Support Services may be
              available to the Customer upon payment of applicable fees, as specified in Customer’s
              Order Form or Foleon’s price list applicable each time. Any Support Services are
              subject to this Agreement and Foleon’s applicable support policies. Foleon may also
              provide onboarding, implementation, and other services under this Agreement. The
              scope, pricing, and other terms for these Professional Services will be specified in
              an Order Form, Order Form exhibit, or other document referencing this Agreement. The
              Customer may use anything delivered as part of these additional services internally
              during its Subscription Term to support its authorized use of the Service, subject to
              the restrictions in Section 4 (Access to the Service) and Section 5.3 (Acceptable Use
              Policy/Prohibited Use) above applicable to the Service(s) itself. Foleon’s ability to
              deliver additional services will depend on the Customer’s reasonable and timely
              cooperation and the accuracy and completeness of any information from the Customer
              needed to deliver the additional services such as copy, images and other content. 8.2.
              Delivery or Completion Periods - In cases where Foleon provides Professional Services,
              the stated delivery or completion periods are by approximation. The delivery or
              completion periods have been established based on the expectation that there will be
              no obstacles for Foleon to perform the Professional Services or to undertake the work.
              8.3. Inability to Perform - If Foleon is unable to perform its obligations in a
              reasonable time as agreed between the Parties when providing Professional Services,
              Foleon will promptly notify the Customer, stating the expected period by which the
              said delivery or completion period will be exceeded. 9. SUBSCRIPTION TERM 9.1.
              Subscription Term - Unless otherwise specified on the Order Form, the Subscription
              Term shall be for a fixed period of twenty-four (24) months. 9.2. Cancellation or
              Termination - The Customer cannot cancel or terminate a Subscription Term prematurely
              except as expressly permitted by Section 12.3 (Termination for Cause) and Section 17.1
              (Performance Warranty). 9.3. Start Date - If a subscription start date is not
              specified on the applicable Order Form, the Subscription Term starts the day that the
              Customer signs the Order Form. 9.4. Renewals – Unless otherwise specified in the
              applicable Order Form, each Subscription Term will renew for a successive 12-month
              period, unless either Party gives the other Party written notice of non-renewal at
              least sixty (60) days before the end of the then-current Subscription Term. Upon
              notice of non-renewal, Customer will not be charged for the next billing cycle but
              will not receive any refunds or credits for amounts that have already been charged.
              9.5. Written Notice - The Customer must give written notice to Foleon via email to
              legal@foleon.com. Foleon must give written notice to the Customer via email to either
              the Customer’s billing email address or to an admin of the Foleon account. 10. FEES
              AND PAYMENT 10.1. Prices and Payment Schedule - The Customer is billed according to
              the package, fees and payment schedule determined in the applicable Order Form. The
              Customer agrees to pay all fees in the agreed currency and in accordance with the
              payment schedule specified in the applicable Order Form. 10.2. Taxes - Foleon’s fees
              are exclusive of all taxes. If Foleon is obligated to collect or pay taxes, the taxes
              will be invoiced from the Customer, unless the Customer provides Foleon with a valid
              tax exemption certificate authorized by the appropriate tax authority. If the Customer
              is required by law to withhold any taxes from its payments to Foleon, the Customer
              must provide Foleon with an official tax receipt or other appropriate documentation to
              support such payments. Any applicable taxes shall be added to the Customer’s invoice.
              10.3. Additional Services - If the Customer wishes to add additional features,
              Add-On’s, seats or Foleon Docs in excess of the applicable Order Form, Foleon may
              charge additional fees. These fees will be agreed between Foleon and the Customer and
              prorated to the end of the Subscription Term. 10.4. Price Changes - Foleon shall have
              the full right to make changes to their pricing. Such price changes shall take effect
              upon the commencement of a new Subscription Term or a renewal thereof. Foleon shall
              inform any Customers with an ongoing Subscription Term of such price changes at least
              ninety (90) days in advance. 10.5 Payment Method - The payment shall be made via wire
              transfer, cheque, paypal or credit card. The message of the payment shall include the
              applicable invoice number or the reference number of the invoice. 11. INVOICING 11.1.
              Standard Invoicing Schedule - The Service(s) is invoiced for a 12-month period at the
              beginning of the Subscription Term. If the Subscription Term exceeds 12-months, the
              Customer will be invoiced in 12-month periods unless otherwise specified on the Order
              Form. 11.2. Invoicing Method - The invoices shall be sent to the billing address
              provided by the Customer. The preferred invoicing method is electronic invoicing via
              email (as pdf) or e-invoice where available. Foleon has the right to add a reasonable
              invoicing fee for traditional paper invoices sent via traditional mail. 11.3. Payment
              Term and Late Payments - The term of invoice payment term is 14 days net from the date
              of issuance of the invoice, unless otherwise specified on the Order Form. Foleon has
              the right to charge a late payment fee and default interest of 1% from the Customer if
              Foleon has not received payment 30 days from the due date. Late payments are subject
              to a service charge of 1.5% per month or the maximum amount allowed by Law, whichever
              is less. 11.4. Blocked Access/Suspension - Foleon has the right to suspend the
              Customer’s accounts and its other obligations under the Agreement and to block access
              to the Service(s) for all users as a result of non-payment. The Customer will be
              informed in writing or by email prior to the Service(s) being blocked. The Customer’s
              liability to pay any invoice does not cease with the termination of this Agreement or
              with the suspension by Foleon of its obligations thereunder. 11.5. Invoicing
              Information - The Customer shall provide Foleon with all necessary reference
              information needed to process each invoice, including a valid billing address. If the
              Customer has not provided such information to Foleon the Customer cannot waive the
              obligation to pay the invoice even if it does not have the reference information
              needed to internally process the payment. 12. TERMINATION 12.1. Termination - Either
              Party may terminate the Agreement with sixty (60) days’ advance written notice prior
              to the Subscription Term end date. If the termination notice is submitted later than
              sixty (60) days prior to the end of the Subscription Term, the subscription shall
              renew as defined in Section 9.4 (Renewals) and the termination shall commence at the
              end of the renewed Subscription Term. 12.2. Termination Notice - The Customer shall
              submit the termination notice via email to legal@foleon.com. Only termination notices
              (i) submitted to the above email address or (ii) for which Customer has received a
              written acceptance or acknowledgement of termination by a Foleon employee, shall be
              deemed a valid termination notice. 12.3. Termination for Cause – Either Party may
              terminate this Agreement (including all Orders) immediately if the other Party i)
              fails to cure a material breach of this Agreement (including a failure to pay fees)
              within 30 days after notice (ii) terminates or suspends its business, (iii) ceases
              operations without a successor or (iv) seeks protection under a bankruptcy,
              receivership, trust deed, creditors’ arrangement, composition or comparable
              proceeding, or if such a proceeding is instituted against that party and not dismissed
              within 60 days. 12.4. Obligations upon Termination - Upon the termination of this
              Agreement: (i) the rights granted by one Party to the other will cease immediately
              (except as set forth in this Section 12 (Termination)) other than limited use of the
              Service to export Customer Content as defined in Section 6.5 (Data Export); and (ii)
              upon request each Party will promptly use commercially reasonable efforts to return or
              destroy Confidential Information of the other Party. 12.5. Surviving Terms - Such
              sections of the Agreement that by their nature are intended to remain in force after
              the termination or expiration of the Agreement shall survive the termination or expiry
              of the Agreement. Such sections include, namely, without limitation, Sections 13
              (Confidentiality), 14 (Intellectual Property Rights), 16 (Indemnification), 18
              (Limitations of Liability) and 20 (General Terms). 13. CONFIDENTIALITY 13.1.
              Confidentiality Obligation - Each Party (as the receiving Party) must: (i) hold in
              confidence and not disclose the other Party’s Confidential Information to Third
              Parties except as permitted by this Agreement; and (ii) only use the other Party’s
              Confidential Information to fulfil its obligations and exercise its rights under this
              Agreement. Each Party may share the other Party’s Confidential Information with its
              Affiliates’, employees, agents or contractors on a legitimate need-to-know basis
              (which, for Foleon, includes the subcontractors referenced in Section 20.4
              (Subcontractors), provided that the Party remains responsible for any recipient’s
              compliance with the terms of this Section 13 (Confidentiality) and that such
              recipients are bound to confidentiality obligations no less protective than those set
              herein. 13.2. Exemptions from Confidentiality - These confidentiality obligations do
              not apply to (and Confidential Information does not include) information that: (i) is
              or becomes public knowledge through no fault of the receiving Party; (ii) was known by
              the receiving Party before it received the Confidential Information; (iii) is
              rightfully obtained by the receiving Party from a third party without breach of any
              confidentiality obligation; or (iv) is independently developed by the receiving Party
              without using the disclosing Party’s Confidential Information, as can be shown by
              documentary evidence. A Party may also disclose the other Party’s Confidential
              Information to the extent required by law or court order, provided it gives advanced
              notice (if permitted by law) and cooperates in any effort by the other Party to obtain
              confidential treatment for the information. 13.3. Equitable Relief - The Parties
              acknowledge that disclosing Confidential Information may cause substantial harm for
              which damages alone may be an insufficient remedy, and so on breach of this Section 13
              (Confidentiality), each Party is entitled to seek appropriate equitable relief in
              addition to any other remedies it may have at law. 14. INTELLECTUAL PROPERTY RIGHTS
              14.1. No Transfer of Intellectual Property Rights - Except as expressly set forth
              herein, this Agreement does not grant either Party any rights, implied or otherwise,
              to the other's Intellectual Property Rights. As between the Parties, the Customer owns
              all Intellectual Property Rights in Customer Data, and Foleon owns all Intellectual
              Property Rights in the Foleon Technology. 15. FOLEON TECHNOLOGY 15.1. Subscription
              Basis - The Service(s) is provided in the form of an online service subscription. The
              Customer acknowledges that it is obtaining only a limited right to use the Service(s)
              and that irrespective of any use of the words “purchase”, “sale” or similar terms, no
              ownership rights are transferred to the Customer under this Agreement. The Customer
              agrees that Foleon (or its suppliers) retain all rights, title and interest (including
              all Intellectual Property Rights) in and to all Foleon Technology and that Foleon
              reserves all rights not specifically granted in this Agreement. Customer further
              acknowledges and agrees that it has no right to obtain a copy of the software behind
              any Service(s). 15.2. Feedback - If the Customer elects to provide any suggestions,
              comments, improvements, information, ideas or other feedback or related materials to
              Foleon (collectively, “Feedback”), the Customer hereby grants Foleon a worldwide,
              perpetual, non-revocable, sublicensable, royalty-free right and license to use, copy,
              disclose, license, distribute, and exploit any Feedback in any format and in any
              manner without any obligation, payment, or restriction based on Intellectual Property
              Rights or otherwise. Foleon will not identify the Customer as the source of the
              Feedback. Nothing in this Agreement limits Foleon’s right to independently use,
              develop, evaluate, or market products, whether incorporating Feedback or otherwise.
              16. INDEMNIFICATION 16.1. Indemnification by Foleon - Foleon agrees to defend and
              indemnify the Customer from and against any Third-Party claims resulting from
              infringement of patent, copyright, trademark, or trade secret by the Service(s)
              itself, as provided by Foleon and used by the Customer in accordance with this
              Agreement. In response to any claim or potential claim of infringement, if required by
              settlement or injunction, or if Foleon determines these actions are reasonably
              necessary to avoid material liability, Foleon may at its option: (i) procure a license
              for the affected portion of the Service(s); (ii) modify the Service(s) so as to avoid
              infringement but be materially equivalent; or (iii) terminate the Order Form for the
              affected Service(s) and refund any subscription fees the Customer has pre-paid for the
              terminated portion of the applicable Subscription Term. Notwithstanding the above,
              Foleon’s obligations under this Section 16 (Indemnification) do not apply to the
              extent infringement results from: (i) Third-Party Products or combinations with these
              items; (ii) modification of the Service(s) by someone other than Foleon or its
              subcontractors; or (iii) use of the Service other than the then-most current release.
              Foleon’s obligations under this Section 16 (Indemnification) also do not apply to use
              in breach of this Agreement, to Customer Data or to Trials and Betas. THIS SECTION 16
              (INDEMNIFICATION) STATES THE SOLE AND EXCLUSIVE REMEDY OF THE CUSTOMER AND THE ENTIRE
              LIABILITY OF FOLEON, OR ANY OF ITS SUPPLIERS, OFFICERS, DIRECTORS, EMPLOYEES,
              SHAREHOLDERS, CONTRACTORS OR REPRESENTATIVES, WITH RESPECT TO ANY CLAIM OF
              INTELLECTUAL PROPERTY INFRINGEMENT. 16.2. Indemnification by Customer - The Customer
              agrees to defend and indemnify Foleon from and against any third-party claims and
              liabilities to the extent resulting from Customer Data or a breach or alleged breach
              of Section 5 (Customer Obligations). 16.3. Conditions for Indemnification - Each
              Party’s defence and indemnification obligations are subject to the indemnifying Party
              receiving: (i) prompt written notice of the claim; (ii) the exclusive right to control
              and direct the investigation, defence, and settlement of the claim; and (iii) all
              reasonable necessary cooperation of the indemnified Party at the indemnifying Party’s
              expense (as to reasonable out-of-pocket costs). The indemnifying Party must not settle
              any claim without the indemnified Party’s prior written consent if the settlement
              would require the indemnified Party to admit fault, pay amounts that the indemnifying
              Party must pay under this Section 16 (Indemnification), or take or refrain from taking
              any action (other than with respect to the Service(s) or features). The indemnified
              Party may participate in a claim through counsel of its own choosing at its own
              expense. 17. WARRANTY; DISCLAIMERS 17.1. Performance Warranty - During the
              Subscription Term, Foleon warrants, for the Customer’s benefit only, that: (i) the
              Service(s) shall perform materially in accordance with the applicable Documentation
              (“Performance Warranty”). The Customer must notify Foleon in writing within thirty
              (30) days of discovery and include a brief reference to the applicable warranty and
              detailed description of the potential breach. If Foleon receives a valid warranty
              claim within this period, it will use commercially reasonable efforts in its
              discretion to repair the affected portion of the Service(s) or re-perform the services
              (as applicable). If Foleon determines this remedy is not commercially reasonable,
              either Party may terminate the applicable Order Form with prompt written notice. Upon
              termination as a result of a warranty claim under this Section 17 (Warranty;
              Disclaimers), the Customer will receive a refund of any subscription fees it has
              pre-paid for the terminated portion of the applicable Subscription Term. The remedy in
              this Section 17 (Warranty; Disclaimers) will be the Customer’s sole and exclusive
              remedy (and Foleon’s sole liability) for any breaches of the Performance Warranty.
              Notwithstanding the above, the Performance Warranty does not cover and Foleon will not
              be responsible for: (i) errors in or resulting from Third-Party Products or
              Third-Party Content; (ii) the Customer’s misuse or failure to follow the
              Documentation; (iii) modifications or services by anyone other than Foleon or its
              subcontractors; (iv) any version of the Service other than the then most recent
              release; or (v) any Trials and Betas. 17.2. NO OTHER WARRANTIES. EXCEPT FOR THE ABOVE
              PERFORMANCE WARRANTY, ALL FOLEON TECHNOLOGY AND RELATED SERVICES ARE PROVIDED “AS IS”
              AND ON AN “AS AVAILABLE” BASIS. NEITHER FOLEON NOR ITS SUPPLIERS MAKE ANY OTHER
              WARRANTIES, EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE, INCLUDING BUT NOT LIMITED TO
              WARRANTIES OF MERCHANTABILITY, TITLE, FITNESS FOR A PARTICULAR PURPOSE, THAT CUSTOMER
              DATA IS PRESERVED WITHOUT LOSS OR THAT FOLEON TECHNOLOGY WILL BE TIMELY, UNINTERRUPTED
              OR ERROR-FREE. THE DISCLAIMERS IN THIS SECTION 17 (WARRANTIES; DISCLAIMERS) WILL APPLY
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, NOTWITHSTANDING ANYTHING TO THE
              CONTRARY IN THIS AGREEMENT. THE CUSTOMER MAY HAVE OTHER STATUTORY RIGHTS. HOWEVER, ANY
              STATUTORILY REQUIRED WARRANTIES UNDER APPLICABLE LAW, IF ANY, WILL BE LIMITED TO THE
              SHORTEST PERIOD AND MAXIMUM EXTENT PERMITTED BY LAW. 18. LIMITATIONS OF LIABILITY
              18.1. NO INDIRECT OR CONSEQUENTIAL DAMAGES. IN NO EVENT WILL EITHER PARTY OR ITS
              SUPPLIERS BE LIABLE FOR ANY LOSS OF USE, LOST OR INACCURATE OR CORRUPTED DATA,
              INTERRUPTION OF BUSINESS, LOST PROFITS, COSTS OF DELAY, REPUTATIONAL HARM, OR ANY
              (OTHER) INDIRECT, SPECIAL, INCIDENTAL, COVER, RELIANCE OR CONSEQUENTIAL DAMAGES OF ANY
              KIND HOWEVER CAUSED, EVEN IF INFORMED IN ADVANCE OF THE POSSIBILITY OF THESE DAMAGES.
              18.2. FOLEON WILL NOT BE RESPONSIBLE OR LIABLE IN ANY MANNER FOR ANY THIRD-PARTY
              PRODUCTS, THIRD-PARTY CONTENT, OR NON-FOLEON SERVICES (INCLUDING FOR ANY DELAYS,
              INTERRUPTIONS, TRANSMISSION ERRORS, SECURITY FAILURES, AND OTHER PROBLEMS CAUSED BY
              THESE ITEMS), FOR PERSONAL DATA OR OTHERWISE REGULATED DATA RECEIVED FROM THE CUSTOMER
              IN BREACH OF THIS AGREEMENT, FOR THE COLLECTION, USE AND DISCLOSURE OF CUSTOMER DATA
              AUTHORIZED BY THIS AGREEMENT, OR FOR DECISIONS OR ACTIONS TAKEN (OR NOT TAKEN) BY THE
              CUSTOMER BASED UPON FOLEON TECHNOLOGY OR FOLEON’S RELATED SERVICES. 18.3. FOLEON HAS
              TAKEN OUT PROFESSIONAL AND CORPORATE LIABILITY INSURANCE ON THE TERMS AND CONDITIONS
              CUSTOMARY IN THE INDUSTRY. WITHOUT PREJUDICE TO THE PROVISIONS OF THIS SECTION 18
              (LIMITATIONS OF LIABILITY), ANY LIABILITY OF FOLEON VIS-A-VIS THE CUSTOMER FOR
              WHATEVER REASON, WILL BE LIMITED TO THE AMOUNT, EQUAL TO THE PAYMENT ACTUALLY MADE
              UNDER FOLEON’S PROFESSIONAL AND CORPORATE LIABILITY INSURANCE. 18.4. IF FOR WHATEVER
              REASON, NO PAYMENT WAS MADE UNDER THE PROFESSIONAL AND CORPORATE INSURANCE OF FOLEON,
              AND FOLEON WOULD BE LIABLE VIS A VIS THE CUSTOMER, FOLEON’S MAXIMUM LIABILITY IN
              CONNECTION WITH AN ATTRIBUTABLE FAILURE IN THE PERFORMANCE OF THIS CONTRACT, WRONGFUL
              ACT OR ANY LEGAL GROUND WHATSOEVER WILL NOT EXCEED IN AGGREGATE THE AMOUNT ACTUALLY
              PAID BY THE CUSTOMER TO FOLEON FOR THE APPLICABLE FOLEON SERVICE OR RELATED SERVICES
              IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, WITH A MAXIMUM AGGREGATE LIABILITY OF
              TWO (2) TIMES THE SUBSCRIPTION COST. EVERY CLAIM AGAINST FOLEON BECOMES TIME BARRED 12
              MONTHS AFTER THE DAMAGED PARTY WAS AWARE OR SHOULD HAVE BEEN AWARE OF THE HARMFUL
              EVENT. 18.5. THE LIABILITY LIMITATIONS IN THIS SECTION 18 (LIMITATIONS OF LIABILITY),
              DO NOT APPLY TO: (i) THE INDEMNITY OBLIGATIONS UNDER SECTION 16 (INDEMNIFICATION); AND
              (ii) THE CUSTOMER’S PAYMENT OBLIGATIONS AS EXPRESSLY PROVIDED IN THIS AGREEMENT. 18.6.
              FOLEON IS NEVER LIABLE FOR DAMAGE OR LOSS OF ANY NATURE WHATSOEVER CAUSED BY HACKING
              BY THIRD PARTIES OR VIRUS, MALWARE, ETC., PROVIDED THAT FOLEON HAS TAKEN ALL
              REASONABLE SECURITY MEASURES CUSTOMARY IN THE INDUSTRY. 18.7. IN CASE THE LAW
              APPLICABLE TO THIS AGREEMENT DOES NOT ALLOW SOME OF THE LIMITATIONS OF LIABILITY IN
              THIS SECTION 18 (LIMITATIONS OF LIABILITY), THIS SECTION 18 (LIMITATIONS OF LIABILITY)
              WILL APPLY TO THE MAXIMUM EXTENT PERMITTED BY LAW. 18.8. THE LIMITATIONS OF LIABILITY
              REFERRED TO IN THIS SECTION 18 (LIMITATIONS OF LIABILITY) DO NOT APPLY IF THE DAMAGE
              OR LOSS IS THE RESULT OF FRAUD, WILFUL MISCONDUCT OR GROSS NEGLIGENCE BY OF EITHER
              PARTY. 19. THIRD-PARTY PRODUCTS AND INTEGRATIONS 19.1. No Liability for Third-Party
              Products - If the Customer decides to enable, access or use Third-Party Products, the
              Customer’s access and use of Third-Party Products shall be governed solely by the
              terms and conditions of such Third-Party Products. The Customer irrevocably waives any
              claim against Foleon with respect to Third-Party Products. Foleon does not warrant or
              support Third-Party Products or Third-Party Content (whether or not these items are
              designated by Foleon as “powered” or “verified” or otherwise) and disclaims all
              responsibility and liability for these items and their access to the Service(s),
              including their modification, deletion, disclosure, or collection of Customer Data.
              Foleon is not responsible in any way for Customer Data once it is transmitted, copied
              or removed from the Service(s) by the Customer or under the Customer’s discretion. 20.
              GENERAL TERMS 20.1. Notice - Any notice or communication under this Agreement must be
              in writing. The Customer must send any notices under this Agreement (including breach
              notices and warranty and indemnity claims) to Foleon, in English, at the following
              address, legal@foleon.com, and include “Attn. Legal Department” in the subject line.
              Foleon may send notices to the email addresses on the Customer’s account or, at
              Foleon’s option, to the Customer’s last-known postal address. Foleon may also provide
              operational notices regarding the Service or other business-related notices through
              conspicuous posting of the notice on Foleon’s website or the Service. Each Party
              consents to receiving electronic notices. Foleon is not responsible for any automatic
              filtering the Customer or its network provider may apply to email notification. 20.2.
              Assignment - This Agreement will bind and inure to the benefit of each Party’s
              permitted successors and assigns. Neither Party may assign this Agreement without the
              advance written consent of the other Party, except that each Party may assign this
              Agreement without consent in connection with a merger, reorganization, acquisition, or
              other transfer of all or substantially all of its assets or voting securities. Any
              attempt to transfer or assign this Agreement except as expressly authorized under this
              Section 20 (General Terms) will be void. 20.3. Publicity - Unless otherwise specified
              in the applicable Order Form, Foleon may use the Customer’s name, logo, and marks to
              identify the Customer as a Customer of Foleon and a user of the relevant Service(s) on
              Foleon’s website and in other marketing materials. Foleon shall cease using the
              Customer’s name, logo and marks upon written notice to publicitynotice@foleon.com. All
              other disclosures about the Customer, including Customer testimonials and case
              studies, are only done so only after collaborating with and obtaining permission with
              the Customer. 20.4. Subcontractors - Foleon may use subcontractors and permit them to
              exercise the rights granted to Foleon in order to provide the Service under this
              Agreement. These subcontractors may include, for example, Foleon’s hosting provider.
              However, subject to all terms and conditions of this Agreement, Foleon will remain
              responsible for: (i) compliance of its subcontractors with the terms of this
              Agreement; and (ii) the overall performance of the Services if and as required under
              this Agreement. 20.5. Independent Contractors - The Parties to this Agreement are
              independent contractors. This Agreement does not create a partnership, joint venture,
              employment, franchise, or agency relationship between the Parties. Neither Party has
              the power to bind the other or incur obligations on the other Party’s behalf without
              the other Party’s prior written consent. 20.6. Force Majeure - Neither Party will be
              liable for any delay or failure to perform its obligation under this Agreement if the
              delay or failure is due to causes beyond its reasonable control, such as a strike,
              blockade, war, act of terrorism, riot, natural disaster, failure or reduction of power
              or telecommunications or data networks or services, pandemics, including Covid19,
              and/or government acts. 20.7. Export - The Customer is responsible for obtaining any
              required export or import authorizations or control laws for the use of any
              Service(s). 20.8. Amendments - Any modification or amendment to this Agreement must be
              made in writing and executed by an authorized representative of each Party. If, during
              the Subscription Term, Foleon modifies the Service-specific terms relevant for a
              specific Service purchased under an Order Form, Foleon will provide notice thereof to
              Customer and the modified version will take effect upon the Customer’s next renewal.
              If Foleon launches new products or optional features that require opt-in acceptance of
              new terms, those terms will apply upon the Customer’s acceptance or use. If Customer
              accepts new Order Forms or Order Form changes following the modification, the changes
              will take effect immediately. However, during a Subscription Term, Foleon may update
              Foleon’s policies, including without limitation the Acceptable Use Policy, and
              Documentation from time-to-time to reflect process improvements or changing practices,
              provided these changes do not substantially diminish the Customer’s rights or create
              substantial additional Customer obligations during a Subscription Term, and these
              changes will take immediate effect from the date of posting. 20.9. No Waiver - Failure
              to enforce any provision of this Agreement will not constitute a waiver. 20.10.
              Severability - If any provision of this Agreement is found by any court of competent
              jurisdiction to be unenforceable or invalid, that provision will be limited to the
              minimum extent necessary so that this Agreement may otherwise remain in effect. 20.11.
              No Third-Party Rights - Nothing in this Agreement confers on any Third-Party the right
              to enforce any provision of this Agreement. Customer acknowledges that each Order Form
              only permits use by and for the legal entity or entities identified in the Order
              Form(s). 20.12. Entire Agreement - This Agreement represents the Parties’ complete and
              exclusive understanding relating to the Agreement’s subject matter. It supersedes all
              prior or contemporaneous oral or written communications, proposals and representations
              with respect to the Foleon Technology or any other subject matter covered by this
              Agreement. Any terms provided by the Customer (including as part of any purchase order
              or other business form used by the Customer) are for administrative purposes only and
              have no legal effect. This Agreement may be signed in counterparts, including by
              electronic copy, each of which will be deemed an original, and all counterparts
              together constituting one and the same Agreement. 20.13. Governing Law, Jurisdiction
              and Region-Specific Terms. Governing law, jurisdiction, and other region-specific
              terms are set out below: 20.13.1. Governing Law and Dispute Resolution - This
              Agreement is governed by the laws of the Netherlands without regard to any conflict of
              law provisions. All disputes will primarily be resolved by negotiation between the
              Parties. If such negotiations fail, any dispute, controversy or claim arising out of
              or relating to this Agreement, or the breach, termination or validity thereof, shall
              be litigated exclusively by the competent court(s) of Amsterdam, The Netherlands. If
              the Customer is not located in the European Union, Foleon may, at its own discretion,
              deviate from the above and may – at its own discretion - demand, and Customer hereby
              irrevocably agrees in advance, that a dispute, controversy or claim arising out of or
              relating to this contract or the breach, termination or validity thereof, shall be
              finally settled by arbitration in accordance with the Arbitration Rules of the laws of
              the Netherlands, irrespective of the place where the contract is performed. The number
              of arbitrators shall be one (1). The seat of arbitration shall be District Court
              Amsterdam, including its preliminary relief judge. The language of the arbitration
              shall be English. The arbitral proceedings and award shall be confidential. 21. ORDER
              OF PRECEDENCE 21.1. The Order of Precedence is i) Order Form(s) ii) DPA iii)
              Acceptable Use Policy, iv) this Agreement, iv) Service Level Agreement, iv) Annexes in
              descending order, v) written communication between the Parties.
            </p>
          </div>
        </div>
      )}

      {showPolicy && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center z-50">
          <div className="bg-white w-[90%] h-[90%]  p-8 relative">
            <button
              onClick={togglePolicy}
              className="absolute top-10 right-10 md:right-24 cursor-pointer border border-gray-400 rounded-full px-8 py-2">
              Close
            </button>

            <h1 className="text-lg text-center fixed pt-3">Privacy Policy</h1>
            <div className="overflow-auto w-[90%] h-[73%] mt-14 px-8 absolute">
              {/* Add your Privacy Policy content here */}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Legal;
